Map<QURAN, String> soras = {
  QURAN.Al_Fatihah: 'الفاتحة',
  QURAN.Al_Baqarah: 'البقرة',
  QURAN.Al_Imran: 'آل عمران',
  QURAN.An_Nisa: 'النساء',
  QURAN.Al_Maidah: 'المائدة',
  QURAN.Al_Anam: 'الأنعام',
  QURAN.Al_Araf: 'الأعراف',
  QURAN.Al_Anfal: 'الأنفال',
  QURAN.At_Taubah: 'التوبة',
  QURAN.Yunus: 'يونس',
  QURAN.Hud: 'هود',
  QURAN.Yusuf: 'يوسف',
  QURAN.Ar_Rad: 'الرعد',
  QURAN.Ibrahim: 'إبراهيم',
  QURAN.Al_Hijr: 'الحجر',
  QURAN.An_Nahl: 'النحل',
  QURAN.Al_Isra: 'الإسراء',
  QURAN.Al_Kahf: 'الكهف',
  QURAN.Maryam: 'مريم',
  QURAN.TaHa: 'طه',
  QURAN.Al_Anbiya: 'الأنبياء',
  QURAN.Al_Hajj: 'الحج',
  QURAN.Al_Muminun: 'المؤمنون',
  QURAN.An_Nur: 'النّور',
  QURAN.Al_Furqan: 'الفرقان',
  QURAN.Ash_Shuara: 'الشعراء',
  QURAN.An_Naml: 'النّمل',
  QURAN.Al_Qasas: 'القصص',
  QURAN.Al_Ankabut: 'العنكبوت',
  QURAN.Ar_Rum: 'الرّوم',
  QURAN.Luqman: 'لقمان',
  QURAN.As_Sajdah: 'السجدة',
  QURAN.Al_Ahzab: 'الأحزاب',
  QURAN.Saba: 'سبأ',
  QURAN.Fatir: 'فاطر',
  QURAN.YaSin: 'يس',
  QURAN.As_Saffat: 'الصافات',
  QURAN.Sad: 'ص',
  QURAN.Az_Zumar: 'الزمر',
  QURAN.Ghafir: 'غافر',
  QURAN.Fussilat: 'فصّلت',
  QURAN.Ash_Shura: 'الشورى',
  QURAN.Az_Zukhruf: 'الزخرف',
  QURAN.Ad_Dukhan: 'الدّخان',
  QURAN.Al_Jathiyah: 'الجاثية',
  QURAN.Al_Ahqaf: 'الأحقاف',
  QURAN.Muhammad: 'محمد',
  QURAN.Al_Fath: 'الفتح',
  QURAN.Al_Hujurat: 'الحجرات',
  QURAN.Qaf: 'ق',
  QURAN.Ad_Dhariyat: 'الذاريات',
  QURAN.At_Tur: 'الطور',
  QURAN.An_Najm: 'النجم',
  QURAN.Al_Qamar: 'القمر',
  QURAN.Ar_Rahman: 'الرحمن',
  QURAN.Al_Waqiah: 'الواقعة',
  QURAN.Al_Hadid: 'الحديد',
  QURAN.Al_Mujadilah: 'المجادلة',
  QURAN.Al_Hashr: 'الحشر',
  QURAN.Al_Mumtahanah: 'الممتحنة',
  QURAN.As_Saff: 'الصف',
  QURAN.Al_Jumuah: 'الجمعة',
  QURAN.Al_Munafiqun: 'المنافقون',
  QURAN.At_Taghabun: 'التغابن',
  QURAN.At_Talaq: 'الطلاق',
  QURAN.At_Tahrim: 'التحريم',
  QURAN.Al_Mulk: 'الملك',
  QURAN.Al_Qalam: 'القلم',
  QURAN.Al_Haqqah: 'الحاقة',
  QURAN.Al_Maarij: 'المعارج',
  QURAN.Nuh: 'نوح',
  QURAN.Al_Jinn: 'الجن',
  QURAN.Al_Muzammil: 'المزّمّل',
  QURAN.Al_Mudathir: 'المدّثر',
  QURAN.Al_Qiyamah: 'القيامة',
  QURAN.Al_Insane: 'الإنسان',
  QURAN.Al_Mursalat: 'المرسلات',
  QURAN.An_Naba: 'النبأ',
  QURAN.An_Naziat: 'النازعات',
  QURAN.Abasa: 'عبس',
  QURAN.At_Takwir: 'التكوير',
  QURAN.Al_Infitar: 'الإنفطار',
  QURAN.Al_Mutaffifeen: 'المطفّفين',
  QURAN.Al_Inshiqaq: 'الإنشقاق',
  QURAN.Al_Buruj: 'البروج',
  QURAN.At_Tariq: 'الطارق',
  QURAN.Al_Ala: 'الأعلى',
  QURAN.Al_Ghashiya: 'الغاشية',
  QURAN.Al_Fajr: 'الفجر',
  QURAN.Al_Balad: 'البلد',
  QURAN.Ash_Shams: 'الشمس',
  QURAN.Al_Layl: 'الليل',
  QURAN.Ad_Duha: 'الضحى',
  QURAN.Ash_Sharh: 'الشرح',
  QURAN.At_Tin: 'التين',
  QURAN.Al_Alaq: 'العلق',
  QURAN.Al_qadr: 'القدر',
  QURAN.Al_Bayyinah: 'البينة',
  QURAN.Az_Zalzala: 'الزلزلة',
  QURAN.Al_Adiyat: 'العاديات',
  QURAN.Al_Qariah: 'القارعة',
  QURAN.At_Takathur: 'التكاثر',
  QURAN.Al_Asr: 'العصر',
  QURAN.Al_Humazah: 'الهمزة',
  QURAN.Al_Fil: 'الفيل',
  QURAN.Al_Quraish: 'قريش',
  QURAN.Al_Maun: 'الماعون',
  QURAN.Al_Kauthar: 'الكوثر',
  QURAN.Al_Kafirun: 'الكافرون',
  QURAN.An_Nasr: 'النصر',
  QURAN.Al_Masad: 'المسد',
  QURAN.Al_Ikhlas: 'الإخلاص',
  QURAN.Al_Falaq: 'الفلق',
  QURAN.An_Nas: 'النّاس',
};

enum QURAN {
  Al_Fatihah,
  Al_Baqarah,
  Al_Imran,
  An_Nisa,
  Al_Maidah,
  Al_Anam,
  Al_Araf,
  Al_Anfal,
  At_Taubah,
  Yunus,
  Hud,
  Yusuf,
  Ar_Rad,
  Ibrahim,
  Al_Hijr,
  An_Nahl,
  Al_Isra,
  Al_Kahf,
  Maryam,
  TaHa,
  Al_Anbiya,
  Al_Hajj,
  Al_Muminun,
  An_Nur,
  Al_Furqan,
  Ash_Shuara,
  An_Naml,
  Al_Qasas,
  Al_Ankabut,
  Ar_Rum,
  Luqman,
  As_Sajdah,
  Al_Ahzab,
  Saba,
  Fatir,
  YaSin,
  As_Saffat,
  Sad,
  Az_Zumar,
  Ghafir,
  Fussilat,
  Ash_Shura,
  Az_Zukhruf,
  Ad_Dukhan,
  Al_Jathiyah,
  Al_Ahqaf,
  Muhammad,
  Al_Fath,
  Al_Hujurat,
  Qaf,
  Ad_Dhariyat,
  At_Tur,
  An_Najm,
  Al_Qamar,
  Ar_Rahman,
  Al_Waqiah,
  Al_Hadid,
  Al_Mujadilah,
  Al_Hashr,
  Al_Mumtahanah,
  As_Saff,
  Al_Jumuah,
  Al_Munafiqun,
  At_Taghabun,
  At_Talaq,
  At_Tahrim,
  Al_Mulk,
  Al_Qalam,
  Al_Haqqah,
  Al_Maarij,
  Nuh,
  Al_Jinn,
  Al_Muzammil,
  Al_Mudathir,
  Al_Qiyamah,
  Al_Insane,
  Al_Mursalat,
  An_Naba,
  An_Naziat,
  Abasa,
  At_Takwir,
  Al_Infitar,
  Al_Mutaffifeen,
  Al_Inshiqaq,
  Al_Buruj,
  At_Tariq,
  Al_Ala,
  Al_Ghashiya,
  Al_Fajr,
  Al_Balad,
  Ash_Shams,
  Al_Layl,
  Ad_Duha,
  Ash_Sharh,
  At_Tin,
  Al_Alaq,
  Al_qadr,
  Al_Bayyinah,
  Az_Zalzala,
  Al_Adiyat,
  Al_Qariah,
  At_Takathur,
  Al_Asr,
  Al_Humazah,
  Al_Fil,
  Al_Quraish,
  Al_Maun,
  Al_Kauthar,
  Al_Kafirun,
  An_Nasr,
  Al_Masad,
  Al_Ikhlas,
  Al_Falaq,
  An_Nas,
}

List<String> grades = [
  'ممتاز',
"جيد جدا",
"جيد",
"مقبول",
"لم يحفظ"];

List<String> sowar = [
  'الفاتحة',
  'البقرة',
  'آل عمران',
  'النساء',
  'المائدة',
  'الأنعام',
  'الأعراف',
  'الأنفال',
  'التوبة',
  'يونس',
  'هود',
  'يوسف',
  'الرعد',
  'إبراهيم',
  'الحجر',
  'النحل',
  'الإسراء',
  'الكهف',
  'مريم',
  'طه',
  'الأنبياء',
  'الحج',
  'المؤمنون',
  'النّور',
  'الفرقان',
  'الشعراء',
  'النّمل',
  'القصص',
  'العنكبوت',
  'الرّوم',
  'لقمان',
  'السجدة',
  'الأحزاب',
  'سبأ',
  'فاطر',
  'يس',
  'الصافات',
  'ص',
  'الزمر',
  'غافر',
  'فصّلت',
  'الشورى',
  'الزخرف',
  'الدّخان',
  'الجاثية',
  'الأحقاف',
  'محمد',
  'الفتح',
  'الحجرات',
  'ق',
  'الذاريات',
  'الطور',
  'النجم',
  'القمر',
  'الرحمن',
  'الواقعة',
  'الحديد',
  'المجادلة',
  'الحشر',
  'الممتحنة',
  'الصف',
  'الجمعة',
  'المنافقون',
  'التغابن',
  'الطلاق',
  'التحريم',
  'الملك',
  'القلم',
  'الحاقة',
  'المعارج',
  'نوح',
  'الجن',
  'المزّمّل',
  'المدّثر',
  'القيامة',
  'الإنسان',
  'المرسلات',
  'النبأ',
  'النازعات',
  'عبس',
  'التكوير',
  'الانفطار',
  'المطفّفين',
  'الانشقاق',
  'البروج',
  'الطارق',
  'الأعلى',
  'الغاشية',
  'الفجر',
  'البلد',
  'الشمس',
  'الليل',
  'الضحى',
  'الشرح',
  'التين',
  'العلق',
  'القدر',
  'البينة',
  'الزلزلة',
  'العاديات',
  'القارعة',
  'التكاثر',
  'العصر',
  'الهمزة',
  'الفيل',
  'قريش',
  'الماعون',
  'الكوثر',
  'الكافرون',
  'النصر',
  'المسد',
  'الإخلاص',
  'الفلق',
  'النّاس'
];
